name: Publish Notebooks to GitHub Pages

on:
  push:
    branches:
      - main
      - preview
      - feature/dabsdeploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: html_publisher
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install nbconvert jupyter-book markdown

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Convert notebooks to HTML
        run: |
          chmod +x .github/scripts/convert_notebooks.py
          python3 .github/scripts/convert_notebooks.py

      - name: Create index page
        run: |
          mkdir -p site
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Customer Segmentation Solution Accelerator</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background: #f8f9fa;
                  }
                  .header {
                      text-align: center;
                      background: linear-gradient(135deg, #FF3621, #FF6B47);
                      color: white;
                      padding: 40px 20px;
                      border-radius: 12px;
                      margin-bottom: 30px;
                  }
                  .notebooks {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                      gap: 20px;
                      margin: 30px 0;
                  }
                  .notebook-card {
                      background: white;
                      padding: 25px;
                      border-radius: 12px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                      transition: transform 0.2s, box-shadow 0.2s;
                  }
                  .notebook-card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 5px 20px rgba(0,0,0,0.15);
                  }
                  .notebook-card h3 {
                      color: #FF3621;
                      margin-top: 0;
                  }
                  .btn {
                      display: inline-block;
                      background: #FF3621;
                      color: white;
                      padding: 10px 20px;
                      text-decoration: none;
                      border-radius: 6px;
                      font-weight: 500;
                      transition: background 0.2s;
                  }
                  .btn:hover {
                      background: #e02d1a;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>Customer Segmentation Solution Accelerator</h1>
                  <p>Modern customer segmentation using Databricks Unity Catalog and Serverless Compute</p>
              </div>
              
              <div class="notebooks">
                  <div class="notebook-card">
                      <h3>📊 Data Generation</h3>
                      <p>Creates synthetic customer data with realistic e-commerce patterns. Generates 10K customers and 250K transactions for analysis.</p>
                      <a href="01_Data_Generation.html" class="btn">View Notebook</a>
                  </div>
                  
                  <div class="notebook-card">
                      <h3>🎯 Segmentation Analysis</h3>
                      <p>Performs RFM analysis combined with behavioral clustering using K-means to identify 6 distinct customer segments.</p>
                      <a href="02_Segmentation_Analysis.html" class="btn">View Notebook</a>
                  </div>
                  
                  <div class="notebook-card">
                      <h3>📈 Business Insights</h3>
                      <p>Interactive Plotly visualizations showing segment performance, ROI projections, and actionable business recommendations.</p>
                      <a href="03_Business_Insights.html" class="btn">View Notebook</a>
                  </div>
              </div>
              
              <div style="text-align: center; margin-top: 40px; padding: 20px; background: white; border-radius: 8px;">
                  <p><strong>Repository:</strong> <a href="https://github.com/databricks-industry-solutions/segmentation" target="_blank">GitHub</a></p>
                  <p style="color: #666; font-size: 0.9em;">© 2025 Databricks, Inc. All rights reserved.</p>
              </div>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
